{% set name = "flask-bcrypt" %}
{% set camelName = "Flask-Bcrypt" %}
{% set bundle = "tar.gz" %}
{% set version = "1.0.0" %}
{% set hash_val = "e622fbd3b0bf63d516b8844fe3431fc30213592412b430036c3928a0c52dfb27" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ camelName }}-{{ version }}.{{ bundle }}
  sha256: {{ hash_val }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip

  run:
    - python
    - flask
    - bcrypt

test:
  imports:
    - flask_bcrypt

about:
  home: https://github.com/maxcountryman/flask-bcrypt
  license_file: LICENSE
  license_family: BSD
  license: BSD 3-Clause
  summary: Bcrypt hashing for Flask.
  dev_url: https://github.com/maxcountryman/flask-bcrypt
  doc_url: https://flask-bcrypt.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - xylar
    - pmlandwehr
