{% set name = "flask-bcrypt" %}
{% set camelName = "Flask-Bcrypt" %}
{% set bundle = "tar.gz" %}
{% set version = "0.7.1" %}
{% set hash_type = "sha256" %}
{% set hash_val = "d71c8585b2ee1c62024392ebdbc447438564e2c8c02b4e57b56a4cafd8d13c5f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ camelName }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip

  run:
    - python
    - flask
    - bcrypt

test:
  imports:
    - flask_bcrypt

about:
  home: https://github.com/maxcountryman/flask-bcrypt
  license_file: LICENSE
  license_family: BSD
  license: BSD 3-Clause
  summary: 'Bcrypt hashing for Flask.'
  dev_url: https://github.com/maxcountryman/flask-bcrypt
  doc_url: https://flask-bcrypt.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
