{% set name = "flask-bcrypt" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Flask-Bcrypt-{{ version }}.tar.gz
  sha256: e622fbd3b0bf63d516b8844fe3431fc30213592412b430036c3928a0c52dfb27

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip

  run:
    - python >=3.7
    - bcrypt >=3.1.1
    - flask

test:
  imports:
    - flask_bcrypt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/maxcountryman/flask-bcrypt
  license_file: LICENSE
  license_family: BSD
  license: BSD-3-Clause
  summary: Bcrypt hashing for Flask.
  dev_url: https://github.com/maxcountryman/flask-bcrypt
  doc_url: https://flask-bcrypt.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - xylar
    - pmlandwehr
