{% set name = "flask-bcrypt" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/Flask-Bcrypt-{{ version }}.tar.gz
  sha256: f07b66b811417ea64eb188ae6455b0b708a793d966e1a80ceec4a23bc42a4369

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - bcrypt >=3.1.1
    - flask

test:
  imports:
    - flask_bcrypt
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/maxcountryman/flask-bcrypt
  license_file: LICENSE
  license_family: BSD
  license: BSD-3-Clause
  summary: Bcrypt hashing for Flask.
  dev_url: https://github.com/maxcountryman/flask-bcrypt
  doc_url: https://flask-bcrypt.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - xylar
    - pmlandwehr
